### ISSUE TITLE
GenericBioEngine: issues with running 3d models

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/archive.bioimage.io#286]
I tried running a couple of 3d models. None of them worked, seeming to fail with different errors. Some displayed the raw data and then froze, others don't even show the raw data.
For a concrete example:  I tried running the following model: https://bioimage.io/#/?id=10.5281%2Fzenodo.6028097  with its sample data
It freezes before even showing the raw data, the console shows the following error:
```
Uncaught (in promise) Error: Error: Error: Traceback (most recent call last):
  File "<exec>", line 238, in form_submit_callback
  File "<exec>", line 167, in run_model
AssertionError
    _decode https://cdn.jsdelivr.net/npm/imjoy-rpc@0.5.9/dist/imjoy-rpc.min.js:1
    _decode https://cdn.jsdelivr.net/npm/imjoy-rpc@0.5.9/dist/imjoy-rpc.min.js:1
    _unwrap https://cdn.jsdelivr.net/npm/imjoy-rpc@0.5.9/dist/imjoy-rpc.min.js:1
    _setupMessageHanlders https://cdn.jsdelivr.net/npm/imjoy-rpc@0.5.9/dist/imjoy-rpc.min.js:1
    _fire https://cdn.jsdelivr.net/npm/imjoy-rpc@0.5.9/dist/imjoy-rpc.min.js:1
    handleEvent https://cdn.jsdelivr.net/npm/imjoy-rpc@0.5.9/dist/imjoy-rpc.min.js:1
```

**Comment by constantinpape** [comment]
works
