### ISSUE TITLE
GenericBioengineApp: error with 

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/archive.bioimage.io#296]
### Summary

when trying out different models, I found that [`fearless-crab`]( https://bioimage.io/#/?id=10.5281%2Fzenodo.6348084) will throw an error when used with [this example data (courtesy of the Gerlich lab)](https://files.ilastik.org/2d_cells_apoptotic_1channel.png). I'm not sure whether the data is wrong, or something else got wrong. It showed a pretty long traceback...

#### Traceback

<details>

```pytb
Failed to run the model, error: Traceback (most recent call last):
  File "/models/bioengine-model-runner/1/model.py", line 236, in start_model_worker
    output_tensors = pred_pipeline(*input_tensors)
  File "/tmp/python_env_qT5KJf/0/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py", line 111, in __call__
    return self.forward(*input_tensors)
  File "/tmp/python_env_qT5KJf/0/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py", line 165, in forward
    prediction_tensors = self.predict(*list(input_sample.values()))
  File "/tmp/python_env_qT5KJf/0/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py", line 135, in predict
    return self._model.forward(*input_tensors)
  File "/tmp/python_env_qT5KJf/0/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py", line 56, in forward
    self.load()
  File "/tmp/python_env_qT5KJf/0/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py", line 41, in load
    self._load(devices=devices or self.default_devices)
  File "/tmp/python_env_qT5KJf/0/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py", line 66, in _load
    self._model = self._load_model(weight_file)
  File "/tmp/python_env_qT5KJf/0/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py", line 32, in _load_model
    return tf.keras.models.load_model(weight_file)
  File "/tmp/python_env_qT5KJf/0/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 212, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/tmp/python_env_qT5KJf/0/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 130, in load
    _read_legacy_metadata(object_graph_def, metadata)
  File "/tmp/python_env_qT5KJf/0/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 179, in _read_legacy_metadata
    node_paths = _generate_object_paths(object_graph_def)
  File "/tmp/python_env_qT5KJf/0/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 204, in _generate_object_paths
    for reference in object_graph_def.nodes[current_node].children:
IndexError: list index (0) out of range
```

</details>

#### Screenshot

<details>

<img width="1300" alt="Screenshot 2022-05-31 at 14 28 08" src="https://user-images.githubusercontent.com/24434157/171175211-d17ef4ed-0f65-42ca-bb4e-8ab5de982bde.png">

</details>

**Comment by oeway** [comment]
Thanks for the report, this is because we only has tensorflow 2 installed in the BioEngine, but the model need tensorflow 1.15.

I will need to disable BioEngine for this model for now: https://github.com/bioimage-io/bioengine-model-runner/commit/57fc0f1409d742d3baef4fed1056ca7680cf41c3

**Comment by k-dominik** [comment]
k, thanks. Are _any_ models in bioimage model zoo with tensorflow 2.x? It is my understanding that this is not the case. Why not put the proper tensorflow version on the server?
