### ISSUE TITLE
App icon pop-ups turn blank after clicking

### ISSUE THREAD

**Issue by qin-yu** [bioimage-io/archive.bioimage.io#377]
1. Go to bioimage.io
2. Click on an app icon on one of the model
    ![Screenshot (19)](https://github.com/bioimage-io/bioimage.io/assets/17722010/c91c3f4e-c636-4351-ab41-6006a88b4917)
3. The popup shows for 1 sec and goes blank
    ![Screenshot (20)](https://github.com/bioimage-io/bioimage.io/assets/17722010/8ba8e76b-599d-4a20-8bad-c9984e311428)

<details>

<summary>Console logs from Chrome</summary>

### Console logs from Chrome

```
chunk-vendors.8c406f94.js:1390 Modal "window-modal-dialog" has scrollable flag set to true but height is not "auto" (670px)
beforeMount @ chunk-vendors.8c406f94.js:1390
chunk-vendors.8c406f94.js:1390 Modal "info-dialog" has scrollable flag set to true but height is not "auto" (600)
beforeMount @ chunk-vendors.8c406f94.js:1390
imjoyCore.js:93 Successfully initialized the engine manager.
pluginManager.js:992 Loading internal plugin "Jupyter-Engine-Manager"...
plugin-service-worker.js:5 Workbox is loaded (plugin service worker)
connection.js:22 connection to the imjoy-rpc peer ojxg38i65z1710165168515 is limited to origin https://lib.imjoy.io.
jailedPlugin.js:388 loaded imjoy-rpc v0.5.9 for Jupyter-Engine-Manager
jailedPlugin.js:800 Plugin Jupyter-Engine-Manager_19gdp1710165168052: Jupyter Engine Manager initialized
pluginManager.js:1001 Jupyter-Engine-Manager plugin loaded.
pluginManager.js:992 Loading internal plugin "WebPythonWorker"...
imjoyLoader.js:155 Using cached imjoy-rpc library v0.5.9.
connection.js:22 connection to the imjoy-rpc peer 4ynwsasvz91710165169011 is limited to origin https://lib.imjoy.io.
jailedPlugin.js:388 loaded imjoy-rpc v0.5.9 for WebPythonWorker
pluginManager.js:1001 WebPythonWorker plugin loaded.
imjoyBasicApp.js:104 ImJoy Core started successfully!
Modal.vue:236 Modal "window-modal-dialog" has scrollable flag set to true but height is not "auto" (500px)
beforeMount @ Modal.vue:236
plugin-service-worker.js:71 cached requirements: Set(669)
 Service worker (core) was activated.
cdn.jsdelivr.net/npm…/imjoy-rpc.min.js:1 Uncaught Error: unrecognized message: [object Object]
    at n (imjoy-rpc.min.js:1:28238)
 Service worker (core) was activated.
imjoyLoader.js:155 Using cached imjoy-rpc library v0.5.9.
connection.js:22 connection to the imjoy-rpc peer t8e8bcdqqb1710165169399 is limited to origin https://lib.imjoy.io.
jailedPlugin.js:388 loaded imjoy-rpc v0.5.9 for Jupyter-Engine-Manager
cdn.jsdelivr.net/npm…/imjoy-rpc.min.js:1 Uncaught Error: unrecognized message: [object Object]
    at n (cdn.jsdelivr.net/npm/imjoy-rpc@0.5.9/dist/imjoy-rpc.min.js:1:28238)
 ImJoy RPC loaded successfully!
imjoyLoader.js:155 Using cached imjoy-rpc library v0.5.9.
connection.js:22 connection to the imjoy-rpc peer hei26jnylr1710165169427 is limited to origin https://lib.imjoy.io.
jailedPlugin.js:388 loaded imjoy-rpc v0.5.9 for WebPythonWorker
 ImJoy RPC loaded successfully!
jailedPlugin.js:800 Plugin Jupyter-Engine-Manager_jv50p1710165169095: Jupyter Engine Manager initialized
app.5948f9c1.js:1 Binder Engine connected!
app.5948f9c1.js:1 Training data not found: ilastik/stradist_dsb_training_data
(anonymous) @ app.5948f9c1.js:1
app.5948f9c1.js:1 Object Object
pluginManager.js:2853 ilastik loaded from https://raw.githubusercontent.com/ilastik/bioimage-io-resources/main/src/ilastik-app.imjoy.html
/#/:1 Third-party cookie will be blocked. Learn more in the Issues tab.
imjoyLoader.js:155 Using cached imjoy-rpc library v0.5.9.
connection.js:22 connection to the imjoy-rpc peer brvlephtau1710165177266 is limited to origin https://lib.imjoy.io.
jailedPlugin.js:388 loaded imjoy-rpc v0.5.9 for ilastik
raw.githubusercontent.com/bioimage-io/spec-bioimage-io/gh-pages/weight_formats_spec.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/bioimage-io/spec-bioimage-io/gh-pages/weight_formats_spec.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
jailedPlugin.js:808 Error in Plugin ilastik_rc8sk1710165176999_xsmw81710165177001: Error occured when loading the window plugin ilastik: Error: SyntaxError: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4)
error @ jailedPlugin.js:808
app.5948f9c1.js:1 Error: SyntaxError: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4)
    at c._decode (rpc.js:787:19)
    at c._decode (rpc.js:831:35)
    at c._unwrap (rpc.js:863:23)
    at rpc.js:260:29
    at ne._fire (utils.js:863:11)
    at ne.<anonymous> (connection.js:65:16)
(anonymous) @ app.5948f9c1.js:1
app.5948f9c1.js:1 Training data not found: ilastik/stradist_dsb_training_data
(anonymous) @ app.5948f9c1.js:1
app.5948f9c1.js:1 Object Object
pluginManager.js:2853 ilastik loaded from https://raw.githubusercontent.com/ilastik/bioimage-io-resources/main/src/ilastik-app.imjoy.html
imjoyLoader.js:155 Using cached imjoy-rpc library v0.5.9.
connection.js:22 connection to the imjoy-rpc peer e5020yf08d1710165186763 is limited to origin https://lib.imjoy.io.
jailedPlugin.js:388 loaded imjoy-rpc v0.5.9 for ilastik
raw.githubusercontent.com/bioimage-io/spec-bioimage-io/gh-pages/weight_formats_spec.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/bioimage-io/spec-bioimage-io/gh-pages/weight_formats_spec.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
jailedPlugin.js:808 Error in Plugin ilastik_14p2k1710165186416_4t9sn1710165186417: Error occured when loading the window plugin ilastik: Error: SyntaxError: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4)
error @ jailedPlugin.js:808
app.5948f9c1.js:1 Error: SyntaxError: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4)
    at c._decode (rpc.js:787:19)
    at c._decode (rpc.js:831:35)
    at c._unwrap (rpc.js:863:23)
    at rpc.js:260:29
    at ne._fire (utils.js:863:11)
    at ne.<anonymous> (connection.js:65:16)
(anonymous) @ app.5948f9c1.js:1
app.5948f9c1.js:1 Training data not found: ilastik/stradist_dsb_training_data
(anonymous) @ app.5948f9c1.js:1
app.5948f9c1.js:1 Object Object
pluginManager.js:2853 deepimagej loaded from https://raw.githubusercontent.com/deepimagej/models/master/src/deepimagej-app.imjoy.html
imjoyLoader.js:155 Using cached imjoy-rpc library v0.5.9.
connection.js:22 connection to the imjoy-rpc peer uwhqjz6w291710165200150 is limited to origin https://lib.imjoy.io.
jailedPlugin.js:388 loaded imjoy-rpc v0.5.9 for deepimagej
raw.githubusercontent.com/bioimage-io/spec-bioimage-io/gh-pages/weight_formats_spec.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/bioimage-io/spec-bioimage-io/gh-pages/weight_formats_spec.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
jailedPlugin.js:808 Error in Plugin deepimagej_3yk1s1710165199884_b9nmc1710165199886: Error occured when loading the window plugin deepimagej: Error: SyntaxError: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4)
error @ jailedPlugin.js:808
app.5948f9c1.js:1 Error: SyntaxError: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4)
    at c._decode (rpc.js:787:19)
    at c._decode (rpc.js:831:35)
    at c._unwrap (rpc.js:863:23)
    at rpc.js:260:29
    at ne._fire (utils.js:863:11)
    at ne.<anonymous> (connection.js:65:16)
(anonymous) @ app.5948f9c1.js:1
```
</details>

**Comment by cfusterbarcelo** [comment]
Hi, 
This seems that is not happening anymore. But just to be sure, @oeway could you check the log and see if there's something weird or confirm that this is solved?
Thanks!
