### ISSUE TITLE
Model cards cannot be expanded

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/archive.bioimage.io#420]
clicking on a model card only leads to removing the cover image:
![image](https://github.com/user-attachments/assets/e599d1e8-17a9-483c-8dec-8ab723d81bae)

I suspect this is due to the website expecting the URL to the RDF to be under `source` rather than `rdf_source` or something like that.. . not sure.

**Comment by oeway** [comment]
Hi I don't reproduce it, how?

**Comment by FynnBe** [comment]
no, idea. now it works... ?!

**Comment by FynnBe** [comment]
no, it's happening again: 

![image](https://github.com/user-attachments/assets/83ad6539-1e1e-4a3d-a5ab-8c4dc6176fe5)

some error I found in the console:
```console
chunk-vendors.e93c4e7e.js:27577 TypeError: e.id.toLowerCase is not a function
    at app.db05d098.js:1:1
    at Array.filter (<anonymous>)
    at c (app.db05d098.js:1:1)
    at st (app.db05d098.js:1:1)
    at app.db05d098.js:1:1
    at l (chunk-vendors.e93c4e7e.js:51127:1)
    at Generator._invoke (chunk-vendors.e93c4e7e.js:51127:1)
    at forEach.e.<computed> [as next] (chunk-vendors.e93c4e7e.js:51127:1)
    at n (chunk-vendors.e93c4e7e.js:1:1)
    at s (chunk-vendors.e93c4e7e.js:1:1)
ot @ chunk-vendors.e93c4e7e.js:27577Understand this error
3D_Unet_notebook.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()Understand this error
chunk-vendors.e93c4e7e.js:27577 TypeError: e.id.toLowerCase is not a function
    at app.db05d098.js:1:1
    at Array.filter (<anonymous>)
    at c (app.db05d098.js:1:1)
    at st (app.db05d098.js:1:1)
    at app.db05d098.js:1:1
    at l (chunk-vendors.e93c4e7e.js:51127:1)
    at Generator._invoke (chunk-vendors.e93c4e7e.js:51127:1)
    at forEach.e.<computed> [as next] (chunk-vendors.e93c4e7e.js:51127:1)
    at n (chunk-vendors.e93c4e7e.js:1:1)
    at s (chunk-vendors.e93c4e7e.js:1:1)
    
```

**Comment by FynnBe** [comment]
opening https://bioimage.io/#/?type=application&id=zero%2Fnotebook_u-net_3d_zerocostdl4mic&tags=zero%2FNotebook_U-Net_3D_ZeroCostDL4Mic seems to work:

![image](https://github.com/user-attachments/assets/3bd9afd3-c086-4e23-afea-e6ca41524406)

but closing the expanded card (with the red x) and then clicking the model card again to expand it again... that's when it fails as described above.

**Comment by oeway** [comment]
Somewhere we messed up with the id, it becomes an integer, I did a quick patch to fix it for now: https://github.com/bioimage-io/bioimage.io/commit/19ee95d1d910d571105d4b43f28a1f7e88a15681

**Comment by FynnBe** [comment]
awesome! can confirm. it now works 👍
